name: Flutter Build and Release APK

on:
  release:
    types: [created]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: actions/setup-flutter@v1
      with:
        flutter-version: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Build APKs
      run: flutter build apk --split-per-abi

    - name: Upload APKs to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: build/app/outputs/flutter-apk/app-arm64-v8a.apk
        asset_name: app-arm64-v8a.apk
        asset_content_type: application/vnd.android.package-archive

    - name: Upload APKs to release (x86_64)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: build/app/outputs/flutter-apk/app-x86_64.apk
        asset_name: app-x86_64.apk
        asset_content_type: application/vnd.android.package-archive

    - name: Upload APKs to release (armeabi-v7a)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: build/app/outputs/flutter-apk/app-armeabi-v7a.apk
        asset_name: app-armeabi-v7a.apk
        asset_content_type: application/vnd.android.package-archive
