name: Flutter Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable # Или укажите конкретную версию Flutter
          channel: stable # Или укажите канал (beta, dev, master)

      - name: Get dependencies
        run: flutter pub get

      - name: Build APKs (split per ABI)
        run: flutter build apk --split-per-abi

      - name: Upload APKs
        uses: actions/upload-artifact@v3
        with:
          name: apks
          path: build/app/outputs/flutter-apk/*.apk

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download APKs
        uses: actions/download-artifact@v3
        with:
          name: apks

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: Automatic release
          draft: false # Установите на true для предварительного релиза
          prerelease: false # Установите на true для пре-релиза

      - name: Upload APKs to Release
        uses: actions/upload-artifact@v3
        with:
          name: apks
          path: ./apks/*.apk
